In [2]:
%matplotlib inline

In [1]:
import pandas as pd
import numpy as np
import math
import matplotlib
import matplotlib.pyplot as plt
import cv2
import os

In [3]:
from math import hypot

In [4]:
import pandas
pandas.__version__

'1.4.3'

In [5]:
from operator import sub, mul
from math import sqrt

In [6]:
df= pd.read_csv('deers_geom.csv', delimiter=',' )

In [7]:
df.dtypes.value_counts()

int64      18
float64     8
object      1
dtype: int64

In [8]:
df.columns

Index(['filename', 'Ax', 'Ay', 'Bx', 'By', 'Cx', 'Cy', 'Dx', 'Dy', 'Ex', 'Ey',
       'Fx', 'Fy', 'Hx', 'Hy', 'Ix', 'Iy', 'Lx', 'Ly', 'Kx', 'Ky', 'Nx', 'Ny',
       'xx', 'xy', 'yx', 'yy'],
      dtype='object')

In [9]:
for c in df:
    if df[c].dtype == 'int64':
        df[c] = df[c].astype('float')

In [13]:
df.dtypes

filename     object
Ax          float64
Ay          float64
Bx          float64
By          float64
Cx          float64
Cy          float64
Dx          float64
Dy          float64
Ex          float64
Ey          float64
Fx          float64
Fy          float64
Hx          float64
Hy          float64
Ix          float64
Iy          float64
Lx          float64
Ly          float64
Kx          float64
Ky          float64
Nx          float64
Ny          float64
xx          float64
xy          float64
yx          float64
yy          float64
AE          float64
AN          float64
BC          float64
BD          float64
BF          float64
BE          float64
CH          float64
CD          float64
CE          float64
CY          float64
AB          float64
AF          float64
CL          float64
DE          float64
DI          float64
DH          float64
EN          float64
EF          float64
FH          float64
dtype: object

In [14]:
#df['AB'] = math.dist( df['Ax'] , df['Bx'])  работает но нам надо длч 4 координат

In [15]:
 #df['AB'] = np.dist([df['Ax'], df['Ay']], [df['Bx'], df['By']]) не работает

In [16]:
#df = df.assign(AB2 = np.sqrt(((df['Ax'] - df['Bx']) ** 2) + ((df['Ay'] - df['By']) ** 2))) проверка - еще 1 вариант

In [17]:
# segments ab af ae an bc bd bf be ch cd ce cy cl de dx di dh en ef fh il ix ly nk

In [18]:
df['AB'] = np.around(np.sqrt(pow((df['Bx'] - df['Ax']),2)+pow((df['By'] - df['Ay']),2)), decimals=1)  
df['AF'] = np.around(np.sqrt(pow((df['Fx'] - df['Ax']),2)+pow((df['Fy'] - df['Ay']),2)), decimals=1)
df['AE'] = np.around(np.sqrt(pow((df['Ex'] - df['Ax']),2)+pow((df['Ey'] - df['Ay']),2)), decimals=1)  
df['AN'] = np.around(np.sqrt(pow((df['Nx'] - df['Ax']),2)+pow((df['Ny'] - df['Ay']),2)), decimals=1)  
df['BC'] = np.around(np.sqrt(pow((df['Cx'] - df['Bx']),2)+pow((df['Cy'] - df['By']),2)), decimals=1)  
df['BD'] = np.around(np.sqrt(pow((df['Dx'] - df['Bx']),2)+pow((df['Dy'] - df['By']),2)), decimals=1)  
df['BF'] = np.around(np.sqrt(pow((df['Fx'] - df['Bx']),2)+pow((df['Fy'] - df['By']),2)), decimals=1)  
df['BE'] = np.around(np.sqrt(pow((df['Ex'] - df['Bx']),2)+pow((df['Ey'] - df['By']),2)), decimals=1)  
df['CH'] = np.around(np.sqrt(pow((df['Hx'] - df['Cx']),2)+pow((df['Hy'] - df['Cy']),2)), decimals=1)  
df['CD'] = np.around(np.sqrt(pow((df['Dx'] - df['Cx']),2)+pow((df['Dy'] - df['Cy']),2)), decimals=1)  
df['CE'] = np.around(np.sqrt(pow((df['Ex'] - df['Cx']),2)+pow((df['Ey'] - df['Cy']),2)), decimals=1)  
df['Cy'] = np.around(np.sqrt(pow((df['yx'] - df['Cx']),2)+pow((df['yy'] - df['Cy']),2)), decimals=1) 
df['CL'] = np.around(np.sqrt(pow((df['Lx'] - df['Cx']),2)+pow((df['Ly'] - df['Cy']),2)), decimals=1) 
df['DE'] = np.around(np.sqrt(pow((df['Dx'] - df['Ex']),2)+pow((df['Dy'] - df['Ey']),2)), decimals=1) 
df['Dx'] = np.around(np.sqrt(pow((df['xx'] - df['Dx']),2)+pow((df['xy'] - df['Dy']),2)), decimals=1)
df['DI'] = np.around(np.sqrt(pow((df['Ix'] - df['Dx']),2)+pow((df['Iy'] - df['Dy']),2)), decimals=1)
df['DH'] = np.around(np.sqrt(pow((df['Hx'] - df['Dx']),2)+pow((df['Hy'] - df['Dy']),2)), decimals=1)
df['EN'] = np.around(np.sqrt(pow((df['Nx'] - df['Ex']),2)+pow((df['Ny'] - df['Ey']),2)), decimals=1)
df['EF'] = np.around(np.sqrt(pow((df['Fx'] - df['Ex']),2)+pow((df['Fy'] - df['Ey']),2)), decimals=1)
df['FH'] = np.around(np.sqrt(pow((df['Hx'] - df['Fx']),2)+pow((df['Hy'] - df['Fy']),2)), decimals=1)
df['IL'] = np.around(np.sqrt(pow((df['Lx'] - df['Ix']),2)+pow((df['Ly'] - df['Iy']),2)), decimals=1)
df['Ix'] = np.around(np.sqrt(pow((df['xx'] - df['Ix']),2)+pow((df['xy'] - df['Iy']),2)), decimals=1)
df['Ly'] = np.around(np.sqrt(pow((df['yx'] - df['Lx']),2)+pow((df['yy'] - df['Ly']),2)), decimals=1)
df['NK'] = np.around(np.sqrt(pow((df['Kx'] - df['Nx']),2)+pow((df['Ky'] - df['Ny']),2)), decimals=1)

In [83]:
df.columns

Index(['filename', 'Ax', 'Ay', 'Bx', 'By', 'Cx', 'Cy', 'Dx', 'Dy', 'Ex', 'Ey',
       'Fx', 'Fy', 'Hx', 'Hy', 'Ix', 'Iy', 'Lx', 'Ly', 'Kx', 'Ky', 'Nx', 'Ny',
       'xx', 'xy', 'yx', 'yy', 'AE', 'AN', 'BC', 'BD', 'BF', 'BE', 'CH', 'CD',
       'CE', 'CY', 'AB', 'AF', 'CL', 'DE', 'DI', 'DH', 'EN', 'EF', 'FH', 'IL',
       'NK'],
      dtype='object')

In [84]:
df_distance =  df[['filename','AE', 'AN', 'BC', 'BD', 'BF', 'BE', 'CH', 'CD',
       'CE', 'CY', 'AB', 'AF', 'CL', 'DE', 'DI', 'DH', 'EN', 'EF', 'FH', 'IL',
       'NK']].copy()

In [85]:
df_distance.columns

Index(['filename', 'AE', 'AN', 'BC', 'BD', 'BF', 'BE', 'CH', 'CD', 'CE', 'CY',
       'AB', 'AF', 'CL', 'DE', 'DI', 'DH', 'EN', 'EF', 'FH', 'IL', 'NK'],
      dtype='object')

In [87]:
df_norm = df_distance.iloc[:,1:].div(df_distance.AB, axis=0)

In [88]:
df_norm
#df[['B','C']].div(df.A, axis=0)

,AE,AN,BC,BD,BF,BE,CH,CD,CE,CY,...,AF,CL,DE,DI,DH,EN,EF,FH,IL,NK
0,0.373727,0.204584,0.123090,0.549236,0.279782,0.626273,0.427278,0.643746,0.684493,0.721562,...,0.721562,0.940436,0.244341,0.735640,0.170204,0.210102,0.348401,0.321944,0.699137,0.701259
1,0.470601,0.262406,0.116868,0.420872,0.277314,0.575688,0.492807,0.516159,0.633862,0.730296,...,0.730296,NaN,0.265847,NaN,NaN,0.209341,0.299625,0.293578,0.540763,0.737594
2,0.369388,0.142508,0.057678,0.364728,0.301124,0.630629,0.316176,0.332530,0.615928,0.699474,...,0.699474,0.931507,0.315754,0.295198,0.473842,0.238574,0.330244,0.229817,0.741660,0.426311
3,0.388170,0.181925,0.288871,0.431797,0.270919,0.614617,0.278181,0.396993,0.678703,0.729209,...,0.729209,0.778258,0.299765,0.401391,0.632646,0.211283,0.343980,0.246266,0.571092,0.412387
4,0.425632,0.231557,0.946294,1.314293,0.256233,0.574454,1.257172,1.844518,1.231301,0.748207,...,0.748207,0.949368,0.741035,0.712090,0.960980,0.246841,0.323258,0.259563,0.787739,1.847251
5,0.377541,0.174827,0.293554,0.621943,0.278672,0.622412,0.674147,0.790714,0.703770,0.721375,...,0.721375,NaN,0.229285,NaN,NaN,0.215013,0.343881,0.328623,0.693723,0.783156
6,0.520842,0.113627,0.094890,0.997796,0.213928,0.499499,0.339479,1.023246,0.481764,0.792084,...,0.792084,NaN,0.612124,NaN,NaN,0.431864,0.315932,0.154409,0.448898,0.546894
7,0.403193,0.236915,0.344365,0.588788,0.268552,0.602056,0.336711,0.627424,0.749016,0.732177,...,0.732177,NaN,0.220513,NaN,NaN,0.166278,0.333576,0.213005,0.629392,0.275842
8,0.391538,0.177063,0.092783,0.404530,0.302428,0.609822,0.326849,0.413917,0.639072,0.697776,...,0.697776,NaN,0.242705,NaN,NaN,0.232365,0.307394,0.232705,0.574179,0.409836
9,0.311086,0.186463,0.469033,0.606429,0.355722,0.688961,0.379195,0.604308,0.751037,0.644325,...,0.644325,NaN,0.152385,0.684672,0.255373,0.124764,0.333380,0.224406,0.697492,0.325462
10,0.242409,0.189689,0.400569,0.543352,0.411681,0.759400,0.362579,0.497739,0.809278,0.590516,...,0.590516,NaN,0.316837,NaN,NaN,0.054658,0.348624,0.255459,0.713787,0.363484
11,0.191955,0.101632,0.404523,0.410535,0.413112,0.808760,0.133982,0.364157,0.815059,0.587031,...,0.587031,NaN,0.461638,0.773404,0.172345,0.094761,0.395648,0.393501,0.863298,NaN
12,0.234488,0.193937,0.079843,0.432992,0.393465,0.765827,0.315827,0.399055,0.746614,0.606535,...,0.606535,0.691654,0.358031,NaN,NaN,0.048268,0.372362,0.301811,0.841890,0.376535
13,0.423945,0.389169,0.104593,0.500398,0.346960,0.601274,0.306345,0.449695,0.576586,0.685957,...,0.685957,0.832227,0.181046,0.723122,0.405628,0.144677,0.266260,0.262809,0.583488,0.494027
14,0.331170,0.207333,0.153904,0.513519,0.338417,0.692299,0.292992,0.467337,0.678347,0.678456,...,0.678456,NaN,0.232533,NaN,NaN,0.139520,0.357993,0.256435,0.562730,0.363400
15,0.379594,0.325095,0.596219,0.706591,0.307985,0.634875,0.389311,0.716096,0.683460,0.699303,...,0.699303,NaN,0.073300,NaN,NaN,0.095057,0.327736,0.197719,NaN,0.575729
16,0.466611,0.266154,0.332813,0.527024,0.249460,0.553687,0.278765,0.558371,0.665866,0.761951,...,0.761951,NaN,0.158900,NaN,NaN,0.217391,0.305669,0.247778,0.577949,0.553327
17,0.251303,0.178803,0.132049,0.438003,0.384457,0.754857,0.369294,0.343390,0.703522,0.637182,...,0.637182,NaN,0.400569,NaN,NaN,0.077397,0.386195,0.446375,0.561365,0.608751
18,0.302910,0.173620,0.325707,0.611289,0.328062,0.701043,0.166975,0.505972,0.667227,0.678583,...,0.678583,NaN,0.189939,NaN,NaN,0.142413,0.376514,0.343371,0.604896,0.555855

In [89]:
df_norm = df_norm.insert(0, 'filename', df_distance['filename'])

In [90]:
df_norm

In [ ]:
#print(to_string(point))

#segments
ab
af
ae
an
bc
bd
bf
be
ch
cd
ce
cy
cl
de
dx
di
dh
en
ef
fh
il
ix
ly
nk

#points
a
b
c
d
e
f
h
i
l
n
k
х
у