In [ ]:
%matplotlib inline

In [ ]:
import pandas as pd
import numpy as np
import math
import matplotlib
import matplotlib.pyplot as plt
import cv2
import os

In [ ]:
from math import hypot

In [ ]:
import pandas
pandas.__version__

'1.4.2'

In [ ]:
from operator import sub, mul
from math import sqrt

In [ ]:
df= pd.read_csv('deers_geom.csv', delimiter=',' )

In [ ]:
df.dtypes.value_counts()

int64      18
float64     8
object      1
dtype: int64

In [ ]:
df.columns

Index(['filename', 'Ax', 'Ay', 'Bx', 'By', 'Cx', 'Cy', 'Dx', 'Dy', 'Ex', 'Ey',
       'Fx', 'Fy', 'Hx', 'Hy', 'Ix', 'Iy', 'Lx', 'Ly', 'Kx', 'Ky', 'Nx', 'Ny',
       'xx', 'xy', 'yx', 'yy'],
      dtype='object')

In [ ]:
for c in df:
    if df[c].dtype == 'int64':
        df[c] = df[c].astype('float')

In [ ]:
df.dtypes

In [ ]:
#df['AB'] = math.dist( df['Ax'] , df['Bx'])  работает но нам надо длч 4 координат

In [ ]:
 #df['AB'] = np.dist([df['Ax'], df['Ay']], [df['Bx'], df['By']]) не работает

In [ ]:
#df = df.assign(AB2 = np.sqrt(((df['Ax'] - df['Bx']) ** 2) + ((df['Ay'] - df['By']) ** 2))) проверка - еще 1 вариант

In [ ]:
df['AB'] = np.around(np.sqrt(pow((df['Bx'] - df['Ax']),2)+pow((df['By'] - df['Ay']),2)), decimals=1)

In [ ]:
df['AF'] = np.around(np.sqrt(pow((df['Fx'] - df['Ax']),2)+pow((df['Fy'] - df['Ay']),2)), decimals=1)

In [ ]:
df

,filename,Ax,Ay,Bx,By,Cx,Cy,Dx,Dy,Ex,...,Ky,Nx,Ny,xx,xy,yx,yy,AB,AF,AB2
0,8-1-1.png,1710,1138,297,1178,224,1406,1127,1461,1182,...,51.0,1446,1020,1075.0,1743.0,143.0,1721.0,1413.6,1020.0,1413.566058
1,8-1-2.png,1340,762,382,810,358,1046,905,1058,921,...,193.0,1101,841,NaN,NaN,NaN,NaN,959.2,700.5,959.201751
2,8-2-1.png,407,2736,6014,3685,5866,4831,2440,4079,2477,...,518.0,1208,2613,2440.0,4720.0,5841.0,5718.0,5686.7,3977.7,5686.743356
3,8-2-2.png,448,2021,4347,1722,4365,2536,1979,2506,1944,...,173.0,1118,1782,2129.0,2894.0,4443.0,2745.0,3910.4,2851.5,3910.447800
4,8-2-3.png,1226,2202,2376,1980,2477,2274,1714,2327,1714,...,183.0,1434,2028,1801.0,2549.0,2574.0,2458.0,1171.2,876.3,1171.231830
5,8-2-4.png,668,2044,2795,2158,2865,2610,1585,2572,1471,...,350.0,1031,1961,NaN,NaN,NaN,NaN,2130.1,1536.6,2130.052816
6,8-3-1.png,785,744,1773,885,1779,1032,1341,1047,1304,...,166.0,875,675,NaN,NaN,NaN,NaN,998.0,790.5,998.010521
7,8-4-1.png,1574,386,210,532,208,785,999,678,1021,...,16.0,1249,382,NaN,NaN,NaN,NaN,1371.8,1004.4,1371.791529
8,8-5-a-1.png,156,727,1617,890,1630,1155,724,954,731,...,83.0,405,651,NaN,NaN,NaN,NaN,1470.1,1025.8,1470.064624
9,8-5-b-c-1.png,2258,785,177,372,189,915,1612,861,1612,...,50.0,1873,694,1542.0,1205.0,NaN,NaN,2121.6,1367.0,2121.586670
10,8-6-1.png,855,339,105,148,80,305,630,378,679,...,43.0,721,279,NaN,NaN,NaN,NaN,773.9,457.0,773.938628
11,8-7-1.png,852,160,154,132,204,303,697,261,718,...,NaN,782,148,687.0,384.0,NaN,NaN,698.6,410.1,698.561379
12,8-7-2.png,1484,527,223,678,265,966,1207,731,1187,...,39.0,1238,515,NaN,NaN,265.0,1292.0,1270.0,770.3,1270.008661
13,8-8-a-1.png,448,267,74,222,89,305,288,261,300,...,74.0,339,169,257.0,311.0,66.0,397.0,376.7,258.4,376.697491
14,8-8b-1-1.png,1081,524,157,492,201,648,772,557,793,...,93.0,922,417,NaN,NaN,NaN,NaN,924.6,627.3,924.553947
15,8-8b-1-2.png,478,663,1240,101,1302,283,868,438,714,...,334.0,624,392,NaN,NaN,NaN,NaN,946.8,662.1,946.830502
16,8-8b-1-3.png,236,508,1055,358,1074,499,583,483,594,...,107.0,414,376,NaN,NaN,NaN,NaN,832.6,634.4,832.622964
17,8-8b-1-4.png,787,407,159,327,193,479,596,458,636,...,28.0,685,358,NaN,NaN,NaN,NaN,633.1,403.4,633.075035
18,8-8b-1-5.png,1304,784,172,421,206,759,934,775,979,...,67.0,1147,650,NaN,NaN,NaN,NaN,1188.8,806.7,1188.777944

In [ ]:
print(to_string(point))

#segments
ab
af
ae
an
bc
bd
bf
be
ch
cd
ce
cy
cl
de
dx
di
dh
en
ef
fh
il
ix
ly
nk

#points
a
b
c
d
e
f
h
i
l
n
k
х
у